version: "3.7"
services:

  # Server PHP
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network

  # Database
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      # - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    networks:
      - laravel-network

  # Webserver
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network

  # Interface for database
  adminer:
    container_name: admin-adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - laravel-network

# Persistind Data
volumes:
  mysqldata:
   driver: local
    
networks:
  laravel-network:
    driver: bridge

  